#!/usr/bin/make -f

image=mysql
namespace=crashvb
tag=SNAPSHOT
name=$(image)-$(tag)

buildargs=--build-arg=org_opencontainers_image_created="$(shell date '+%Y%m%d%H%M')" \
	--build-arg=org_opencontainers_image_revision="$(shell git rev-parse --short=12 --verify HEAD)"

runargs=--publish-all

testargs=--env=EP_RSA_KEY_SIZE=2048 \
	--env=MYSQL_DATABASE=testdb \
	--env=MYSQL_USER=TESTUSER
